baseURL = 'https://spectre-pro.github.io/'
languageCode = 'zh-hk'
defaultContentLanguage = 'zh-hk'
title = 'SPECTRE'
hasCJKLanguage = false
enableEmoji = true
theme = 'hugo-theme-fluidity'

[caches]
  [caches.images]
    dir = ':cacheDir/images'